
# Importing modules allows us to use functions not included in base Python.
# We will be importing the time, random, and system modules for later use.

from time import sleep

def titleSequence():
    # The sleep(time) function allows us to create a delay between lines
    print("          You should really hurry up           "), sleep(.3)
    print(".     "), sleep(.5)
    print(".     "), sleep(.5)
    print(".     "), sleep(.5)
    print("    You're gonna have to go faster than that    "), sleep(.3)
    print(".     "), sleep(.5)
    print(".     "), sleep(.5)
    print(".     "), sleep(.5)
    print("         HURRY UP IT'S GETTING CLOSER            "), sleep(.3)
    print("!     "), sleep(.5)
    print("!     "), sleep(.5)
    print("!     "), sleep(.5)
    print("        ____   __    __ __     __ __  __  __ "), sleep(.3)
    print("       / __ \ / /   / /   |   / /  //  //  /  "), sleep(.3)
    print("      / /_/ // /   / / /| |  / /  //  //  /   "), sleep(.3)
    print("     / _ _/ / /   / / / | | / /  //  //  /     "), sleep(.3)
    print("    / / \ \/ /___/ / /  | |/ /__//__//__/     "), sleep(.3)
    print("   /_/  /_/\______/_/   |___/__//__//__/      "), sleep(1)
    print("")
    print("")

def hallway(direction):
#1
    if direction == 1:
        print(" \                                        / "), sleep(.1)
        print("  \                                      /  "), sleep(.1)
        print("   \                                    /   "), sleep(.1)
        print("    \__________________________________/    "), sleep(.1)
        print("    |\                                /|    "), sleep(.1)
        print("    | \                              / |    "), sleep(.1)
        print("    |  \                            /  |    "), sleep(.1)
        print("    |   \                          /   |    "), sleep(.1)
        print("    |    \                        /    |    "), sleep(.1)
        print("    |     \                      /     |    "), sleep(.1)
        print("    |      \                    /      |    "), sleep(.1)
        print("    |       \__________________/       |    "), sleep(.1)
        print("    |       |\                /|       |    "), sleep(.1)
        print("    |       | \              / |       |    "), sleep(.1)
        print("    |       |  \            /  |       |    "), sleep(.1)
        print("    |       |   \__________/   |       |    "), sleep(.1)
        print("    |       |   |\        /|   |       |    "), sleep(.1)
        print("    |       |   | |\____/| |   |       |    "), sleep(.1)
        print("    |       |   | | \__/ | |   |       |    "), sleep(.1)
        print("    |       |   | | |__| | |   |       |    "), sleep(.1)
        print("    |       |   | |/____\| |   |       |    "), sleep(.1)
        print("    |       |   | /      \ |   |       |    "), sleep(.1)
        print("    |       |   |/________\|   |       |    "), sleep(.1)
        print("    |       |   /          \   |       |    "), sleep(.1)
        print("    |       |  /            \  |       |    "), sleep(.1)
        print("    |       | /              \ |       |    "), sleep(.1)
        print("    |       |/________________\|       |    "), sleep(.1)
        print("    |       /                  \       |    "), sleep(.1)
        print("    |      /                    \      |    "), sleep(.1)
        print("    |     /                      \     |    "), sleep(.1)
        print("    |    /                        \    |    "), sleep(.1)
        print("    |   /                          \   |    "), sleep(.1)
        print("    |  /                            \  |    "), sleep(.1)
        print("    | /                              \ |    "), sleep(.1)
        print("    |/________________________________\|    "), sleep(.1)
        print("    /                                  \    "), sleep(.1)
        print("   /                                    \   "), sleep(.1)
        print("  /                                      \  "), sleep(.1)
        print(" /                                        \ "), sleep(.1)

#2
    elif direction == 2:
        print(" \                                        / "), sleep(.1)
        print("  \                                      /  "), sleep(.1)
        print("   \                                    /   "), sleep(.1)
        print("    \__________________________________/    "), sleep(.1)
        print("    |\                                /|    "), sleep(.1)
        print("    | \                              / |    "), sleep(.1)
        print("    |  \                            /  |    "), sleep(.1)
        print("    |   \                          /   |    "), sleep(.1)
        print("    |    \                        /    |    "), sleep(.1)
        print("    |     \                      /     |    "), sleep(.1)
        print("    |      \                    /      |    "), sleep(.1)
        print("    |       \__________________/       |    "), sleep(.1)
        print("    |       |\                /|       |    "), sleep(.1)
        print("    |       | \              / |       |    "), sleep(.1)
        print("    |       |  \            /  |       |    "), sleep(.1)
        print("    |       |   \__________/___|       |    "), sleep(.1)
        print("    |       |   |\        /|   |       |    "), sleep(.1)
        print("    |       |   | |\____/| |   |       |    "), sleep(.1)
        print("    |       |   | | \__/ | |   |       |    "), sleep(.1)
        print("    |       |   | | |__| | |   |       |    "), sleep(.1)
        print("    |       |   | |/____\| |   |       |    "), sleep(.1)
        print("    |       |   | /      \ |   |       |    "), sleep(.1)
        print("    |       |   |/________\|___|       |    "), sleep(.1)
        print("    |       |   /          \   |       |    "), sleep(.1)
        print("    |       |  /            \  |       |    "), sleep(.1)
        print("    |       | /              \ |       |    "), sleep(.1)
        print("    |       |/________________\|       |    "), sleep(.1)
        print("    |       /                  \       |    "), sleep(.1)
        print("    |      /                    \      |    "), sleep(.1)
        print("    |     /                      \     |    "), sleep(.1)
        print("    |    /                        \    |    "), sleep(.1)
        print("    |   /                          \   |    "), sleep(.1)
        print("    |  /                            \  |    "), sleep(.1)
        print("    | /                              \ |    "), sleep(.1)
        print("    |/________________________________\|    "), sleep(.1)
        print("    /                                  \    "), sleep(.1)
        print("   /                                    \   "), sleep(.1)
        print("  /                                      \  "), sleep(.1)
        print(" /                                        \ "), sleep(.1)
#3
    elif direction == 3:
        print(" \                                        / "), sleep(.1)
        print("  \                                      /  "), sleep(.1)
        print("   \                                    /   "), sleep(.1)
        print("    \__________________________________/    "), sleep(.1)
        print("    |\                                /|    "), sleep(.1)
        print("    | \                              / |    "), sleep(.1)
        print("    |  \                            /  |    "), sleep(.1)
        print("    |   \                          /   |    "), sleep(.1)
        print("    |    \                        /    |    "), sleep(.1)
        print("    |     \                      /     |    "), sleep(.1)
        print("    |      \                    /      |    "), sleep(.1)
        print("    |       \__________________/       |    "), sleep(.1)
        print("    |       |\                /|       |    "), sleep(.1)
        print("    |       | \              / |       |    "), sleep(.1)
        print("    |       |  \            /  |       |    "), sleep(.1)
        print("    |       |___\__________/   |       |    "), sleep(.1)
        print("    |       |   |\        /|   |       |    "), sleep(.1)
        print("    |       |   | |\____/| |   |       |    "), sleep(.1)
        print("    |       |   | | \__/ | |   |       |    "), sleep(.1)
        print("    |       |   | | |__| | |   |       |    "), sleep(.1)
        print("    |       |   | |/____\| |   |       |    "), sleep(.1)
        print("    |       |   | /      \ |   |       |    "), sleep(.1)
        print("    |       |___|/________\|   |       |    "), sleep(.1)
        print("    |       |   /          \   |       |    "), sleep(.1)
        print("    |       |  /            \  |       |    "), sleep(.1)
        print("    |       | /              \ |       |    "), sleep(.1)
        print("    |       |/________________\|       |    "), sleep(.1)
        print("    |       /                  \       |    "), sleep(.1)
        print("    |      /                    \      |    "), sleep(.1)
        print("    |     /                      \     |    "), sleep(.1)
        print("    |    /                        \    |    "), sleep(.1)
        print("    |   /                          \   |    "), sleep(.1)
        print("    |  /                            \  |    "), sleep(.1)
        print("    | /                              \ |    "), sleep(.1)
        print("    |/________________________________\|    "), sleep(.1)
        print("    /                                  \    "), sleep(.1)
        print("   /                                    \   "), sleep(.1)
        print("  /                                      \  "), sleep(.1)
        print(" /                                        \ "), sleep(.1)
#4
    elif direction == 4:
        print(" \                                        / "), sleep(.1)
        print("  \                                      /  "), sleep(.1)
        print("   \                                    /   "), sleep(.1)
        print("    \__________________________________/    "), sleep(.1)
        print("    |\                                /|    "), sleep(.1)
        print("    | \                              / |    "), sleep(.1)
        print("    |  \                            /  |    "), sleep(.1)
        print("    |   \                          /   |    "), sleep(.1)
        print("    |    \                        /    |    "), sleep(.1)
        print("    |     \                      /     |    "), sleep(.1)
        print("    |      \                    /      |    "), sleep(.1)
        print("    |       \__________________/       |    "), sleep(.1)
        print("    |       |\                /|       |    "), sleep(.1)
        print("    |       | \              / |       |    "), sleep(.1)
        print("    |       |  \            /  |       |    "), sleep(.1)
        print("    |       |___\__________/___|       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |___|__________|___|       |    "), sleep(.1)
        print("    |       |   /          \   |       |    "), sleep(.1)
        print("    |       |  /            \  |       |    "), sleep(.1)
        print("    |       | /              \ |       |    "), sleep(.1)
        print("    |       |/________________\|       |    "), sleep(.1)
        print("    |       /                  \       |    "), sleep(.1)
        print("    |      /                    \      |    "), sleep(.1)
        print("    |     /                      \     |    "), sleep(.1)
        print("    |    /                        \    |    "), sleep(.1)
        print("    |   /                          \   |    "), sleep(.1)
        print("    |  /                            \  |    "), sleep(.1)
        print("    | /                              \ |    "), sleep(.1)
        print("    |/________________________________\|    "), sleep(.1)
        print("    /                                  \    "), sleep(.1)
        print("   /                                    \   "), sleep(.1)
        print("  /                                      \  "), sleep(.1)
        print(" /                                        \ "), sleep(.1)
#5
    elif direction == 5:
        print(" \                                        / "), sleep(.1) 
        print("  \                                      /  "), sleep(.1)
        print("   \                                    /   "), sleep(.1)
        print("    \__________________________________/    "), sleep(.1)
        print("    |\                                /|    "), sleep(.1)
        print("    | \                              / |    "), sleep(.1)
        print("    |  \                            /  |    "), sleep(.1)
        print("    |   \                          /   |    "), sleep(.1)
        print("    |    \                        /    |    "), sleep(.1)
        print("    |     \                      /     |    "), sleep(.1)
        print("    |      \                    /      |    "), sleep(.1)
        print("    |       \__________________/       |    "), sleep(.1)
        print("    |       |\                /|       |    "), sleep(.1)
        print("    |       | \              / |       |    "), sleep(.1)
        print("    |       |  \            /  |       |    "), sleep(.1)
        print("    |       |   \__________/   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |    ()    |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |__________|   |       |    "), sleep(.1)
        print("    |       |   /          \   |       |    "), sleep(.1)
        print("    |       |  /            \  |       |    "), sleep(.1)
        print("    |       | /              \ |       |    "), sleep(.1)
        print("    |       |/________________\|       |    "), sleep(.1)
        print("    |       /                  \       |    "), sleep(.1)
        print("    |      /                    \      |    "), sleep(.1)
        print("    |     /                      \     |    "), sleep(.1)
        print("    |    /                        \    |    "), sleep(.1)
        print("    |   /                          \   |    "), sleep(.1)
        print("    |  /                            \  |    "), sleep(.1)
        print("    | /                              \ |    "), sleep(.1)
        print("    |/________________________________\|    "), sleep(.1)
        print("    /                                  \    "), sleep(.1)
        print("   /                                    \   "), sleep(.1)
        print("  /                                      \  "), sleep(.1)
        print(" /                                        \ "), sleep(.1)

    elif direction == 6:
        print(" \                                        / "), sleep(.1) 
        print("  \                                      /  "), sleep(.1)
        print("   \                                    /   "), sleep(.1)
        print("    \__________________________________/    "), sleep(.1)
        print("    |\                                /|    "), sleep(.1)
        print("    | \                              / |    "), sleep(.1)
        print("    |  \                            /  |    "), sleep(.1)
        print("    |   \                          /   |    "), sleep(.1)
        print("    |    \                        /    |    "), sleep(.1)
        print("    |     \                      /     |    "), sleep(.1)
        print("    |      \                    /      |    "), sleep(.1)
        print("    |       \__________________/       |    "), sleep(.1)
        print("    |       |\                /|       |    "), sleep(.1)
        print("    |       | \              / |       |    "), sleep(.1)
        print("    |       |  \            /  |       |    "), sleep(.1)
        print("    |       |   \__________/   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |          |   |       |    "), sleep(.1)
        print("    |       |   |__________|   |       |    "), sleep(.1)
        print("    |       |   /          \   |       |    "), sleep(.1)
        print("    |       |  /            \  |       |    "), sleep(.1)
        print("    |       | /              \ |       |    "), sleep(.1)
        print("    |       |/________________\|       |    "), sleep(.1)
        print("    |       /                  \       |    "), sleep(.1)
        print("    |      /                    \      |    "), sleep(.1)
        print("    |     /                      \     |    "), sleep(.1)
        print("    |    /                        \    |    "), sleep(.1)
        print("    |   /                          \   |    "), sleep(.1)
        print("    |  /                            \  |    "), sleep(.1)
        print("    | /                              \ |    "), sleep(.1)
        print("    |/________________________________\|    "), sleep(.1)
        print("    /                                  \    "), sleep(.1)
        print("   /                                    \   "), sleep(.1)
        print("  /                                      \  "), sleep(.1)
        print(" /                                        \ "), sleep(.1)


def DeathScreen():

    print("                  _,.-------.,_                 "), sleep(.1)
    print("              ,;~'             '~;,             "), sleep(.1)
    print("            ,;                     ;,           "), sleep(.1)
    print("           ;                         ;          "), sleep(.1)
    print("          ,'                         ',         "), sleep(.1)
    print("         ,;                           ;,        "), sleep(.1)
    print("         ; ;      .           .      ; ;        "), sleep(.1)
    print("         | ;   ______       ______   ; |        "), sleep(.1)
    print("         |  `/~'     ~' . '~     '~\'  |        "), sleep(.1)
    print("         |  ~  ,-~~~^~, | ,~^~~~-,  ~  |        "), sleep(.1)
    print("          |   |        }:{        |   |         "), sleep(.1)
    print("          |   l       / | \       !   |         "), sleep(.1)
    print("          .~  (__,.--' .^. '--.,__)  ~.         "), sleep(.1)
    print("          |     ---;' / | \ `;---     |         "), sleep(.1)
    print("           \__.       \/^\/       .__/          "), sleep(.1)
    print("            V| \                 / |V           "), sleep(.1)
    print("             | |T~\___!___!___/~T| |            "), sleep(.1)
    print("             | |`IIII_I_I_I_IIII'| |            "), sleep(.1)
    print("             |  \,III I I I III,/  |            "), sleep(.1)
    print("              \   `~~~~~~~~~~'    /             "), sleep(.1)
    print("                \   .       .   /               "), sleep(.1)
    print("                  \.    ^    ./                 "), sleep(.1)
    print("                    ^~~~^~~~^                   "), sleep(.1)
    
def outDoors():

    print("      ` : | | | |:  ||  :     `  :  |  |+|: | : : :|   .        `           "), sleep(.1)
    print("      ` : | :|  ||  |:  :    `  |  | :| : | : |:   |  .                    :"), sleep(.1)
    print("         .' ':  ||  |:  |  '       ` || | : | |: : |   .  `           .   :."), sleep(.1)
    print("                `'  ||  |  ' |   *    ` : | | :| |*|  :   :               :|"), sleep(.1)
    print("        *    *       `  |  : :  |  .      ` ' :| | :| . : :         *   :.||"), sleep(.1)
    print("             .`            | |  |  : .:|       ` | || | : |: |          | ||"), sleep(.1)
    print("      '          .         + `  |  :  .: .         '| | : :| :    .   |:| ||"), sleep(.1)
    print("         .                 .    ` *|  || :       `    | | :| | :      |:| | "), sleep(.1)
    print(" .                .          .        || |.: *          | || : :     :|||   "), sleep(.1)
    print("        .            .   . *    .   .  ` |||.  +        + '| |||  .  ||`    "), sleep(.1)
    print("     .             *              .     +:`|!             . ||||  :.||`     "), sleep(.1)
    print(" +                      .                ..!|*          . | :`||+ |||`      "), sleep(.1)
    print("     .                         +      : |||`        .| :| | | |.| ||`     . "), sleep(.1)
    print("       *     +   '               +  :|| |`     :.+. || || | |:`|| `         "), sleep(.1)
    print("                            .      .||` .    ..|| | |: '` `| | |`  +        "), sleep(.1)
    print("  .       +++                      ||        !|!: `       :| |              "), sleep(.1)
    print("              +         .      .    | .      `|||.:      .||    .      .    "), sleep(.1)
    print("          '                           `|.   .  `:|||   + ||'     `          "), sleep(.1)
    print("  __    +      *                         `'       `'|.    `:                "), sleep(.1)
    print("''  `---'''----....____,..^---`^``----.,.___          `.    `.  .    ____,.,"), sleep(.1)
    print("    ___,--'""`---''   ^  ^ ^        ^       ''''---,..___ __,..---'''       "), sleep(.1)
    print("--''                           ^                         ``--..,__ ___  __ _"), sleep(.1)

def TryAgain():
    while True:
        redo = input('Try Again?\nYES or NO').lower()
        if redo in ['yes','no']:
            break
        else:
            print("I don't understand what you mean")
    if redo == 'yes':
        TheGame()

def TheGame():
    titleSequence()
    print('Running'), sleep(.5)
    print('.'), sleep(1)
    print('Running'), sleep(.5)
    print('.'), sleep(1)
    print('Running'), sleep(.5)
    print('.'), sleep(1)
    print('You hear a low scurrying behind you. There is definitely something back there.'), sleep(2)
    print('.'), sleep(1)
    print("More Running"), sleep(.5)
    print('.'), sleep(1)
    hallway(4)
    print('You arrive at a fork in the path.'), sleep(.1)
    print('.'), sleep(1)
    print('You can hear something approaching you from behind.')
    print('.'), sleep(1)
    while True:
        step1 = input('No time to turn around and examine. Which way do you go? \n      LEFT or RIGHT: ').lower()
        if step1 in ['left','right']:
            break
        else:
            print('.'), sleep(.3)
            print('Stop talking nonsense, you need to decide!')
            print('.'), sleep(.3)
    if step1 == 'left':
        print('You go left...'), sleep(.3)
        print('.'), sleep(1)
        print('Gotta keep running.'), sleep(2)
        print('.'), sleep(1)
    else:
        print('You go right...'), sleep(.3)
        print('.'), sleep(1)
        print('Gotta keep running.'), sleep(2)
        print('.'), sleep(1)
        print('The noises behind you are getting louder.'), sleep(1)
        print('.'), sleep(1)
        print('How did you get here? Where are you?'),sleep(2)
        print('.'), sleep(1)
        print('No time to think. You have to focus on running.'), sleep(1)
        print('.'), sleep(1)
        hallway(5)
        print('Before you know it you are at a dead end... wait there is a button on the wall.'), sleep(1)
        print('.'), sleep(1)
        print('What will you do? This place could have traps'), sleep(.5)
        print('.'), sleep(1)
        while True:
            step2 = input('PUSH the button or WAIT: ').lower()
            if step2 in ['push','wait']:
                break
            else:
                print('.'), sleep(.3)
                print('What language is that? You need you hurry')
                print('.'), sleep(.3)
        if step2 == 'push':
            outDoors()
            print("               You made it outside, you feel like you escaped..."), sleep(1)
            print('.'), sleep(1)
            print("      But you can't seem to stop running, its like your body won't let you."), sleep(1)
            print('.'), sleep(1)
            print('.'), sleep(1)
            print("      Maybe you'll stay like this for a while, the view isn't so bad anyway."), sleep(4)
            print('.'), sleep(1)
            print('.'), sleep(1)
            print('.'), sleep(1)
            print('.'), sleep(1)
            print("                               Thanks for playing :)")
            TryAgain()
        else:
            DeathScreen()
            print("      You shouldn't have waited, whatever it was    \n      got you before you could turn around\n\n            You are DEAD")
            TryAgain()


TheGame()
    
